site_name: FOM RL Ship Navigation – Q-Learning

nav:
  - Startseite: index.md
  - Setup: setup.md
  - Funktionsweise: funktionsweise.md
  - Training: training.md
  - Visualisierung: visualisierung.md
  - Entwicklung: dokumentation.md

theme:
  name: material