site_name: FOM RL Ship Navigation – Q-Learning

nav:
  - Home: index.md
  - Funktionsweise: funktionsweise.md
  - Visualisierung: visualisierung.md
  - Training: training.md
  - Dokumentation: how-to-push.md

theme:
  name: material